#!/bin/bash


##Lines with two # marks are explianations of what things are,
## and lines with only one are the optional settings. Don't change them
##unless you know what you are doing.

##kill and reset both wifi interface MAC addresses
##unmark only if you want static mac addresses and static IPs
#ifconfig wlan0 down && ifconfig wlan1 down
#ifconfig wlan0 hw ether 00:11:22:33:44:55
#ifconfig wlan1 hw ether 11:22:22:33:33:55
#ifconfig wlan0 up && ifconfig wlan1 up

##reset ip addresses of both interfaces to mask where data or hacks came from
#ifconfig wlan0 194.27.11.5 netmask 255.255.255.0
#ifconfig wlan1 102.88.124.67 netmask 255.255.255.0


##set up dnsmask with application dnsmasq
##Experimental
#dnsmasq -C /etc/dnsmasq.d/dnsmasq.conf

##run go spider with selective input from cmd
#echo Enter the nasme of the website that you want to crawl anonymously :
#read WEBSITE
#echo Enter the file that you want to save your findings to : 
#read OUTPUT

## Python script to make computer or terminal completely anonymous by
##changing the Mac address of interfaces and IP addresses of all interfaces
#sudo python3 main.py

##pause to allow user to reestablish connection
#echo Make sure that you are connected to internet as reset may disconnect you
#echo When you are ready press enter on your keyboard :
#read CONTINUING

##Runs the application gospider which is a web creawler
##decisions time
read -n1 -p "What platform do you want to perform the crawl? [t,w,m,f,c]" platform
case $platform in
    t|T) echo tor ;;
    w|W) echo web ;;
    m|M) echo midori ;;
    f|F) echo firefox ;;
    c|C) echo chromium ;;
esac

read -n1 -p "do you want to run multiple threads? [y,n]" choice1
case $choice1 in
    y|Y) echo yes ;;
    n|N) echo no ;;
esac

if [ $choice1==y ]
    then
    read -n1 -p "How many threads do you want to run? Default 1  [2,3,4,5,6,7,8,9,10]" threads
         case $threads in
             2) $thread==2 ;;
             3) $thread==3 ;;
             4) $thread==4 ;;
	     5) $thread==5 ;;
	     6) $thread==6 ;;
	     7) $thread==7 ;;
	     8) $thread==8 ;;
	     9) $thread==9 ;;
         esac
elif [$choice1==n]
    then
    $thread==1
fi

read -n1 -p "Do you want a depth recursion deeper than 1? [y|n]" choice2
case $choice2 in
    y|Y) echo yes ;;
    n|N) echo no ;;
esac

if [ "$choice2"=="y" ]
    then
    read n1 -p "What would you like to set the depth at? default 1, 0 means infinite [0,2,3,4,5,6,7,8,9]" depth
        case depth in
            0) echo -d 0 ;;
            2) echo -d 2 ;;
	    3) echo -d 3 ;;
	    4) echo -d 4 ;;
	    5) echo -d 5 ;;
	    6) echo -d 6 ;;
	    7) echo -d 7 ;;
	    8) echo -d 8 ;;
	    9) echo -d 9 ;;
        esac
else
    $depth==1
gospider -s $WEBSITE -o $OUTPUT -u $platform -t $thread -d $depth -K 10 --sitemap True -w -r -v
